baseURL = "https://neilruplayer.github.io/"
title = "Neil Ruplayer | Chercheur"
theme = "hugo-profile"

[params]
  # Biographie courte
  title = "Neil Rueplayer"
  subtitle = "Associate Professor | Department of Computer Applications & Mathematical Sciences"
  # Cette description courte apparaît souvent sous le nom
  description = "North-Eastern Hill University (NEHU), Shillong, India"
#  custom_js = []
#  custom_css = []
#  showTableOfContents = false
  
  [params.section]
    # Désactive les sections qui pourraient chercher des données inexistantes
    about = true
    experience = false
    education = false
    projects = false
  # Liens réseaux sociaux (optionnel)
  [[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    url = "https://medium.com/@NeilRueplayer"

[[menu.main]]
  name = "Teaching"
  url = "/teaching/"
  weight = 1
[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 2
[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
